apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-dec6-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/chatbot-dec6-2:8dd44b47a9f650627612156ec138839a8d3b56aa@sha256:517543aecf2027c59e46cb120def6e2cd732afbbac97dc1c9a2fa5f4ae37b33a # use pre-built to bootstrap 
          name: app-inference
